mac[6], byte ip[4])rhs)pin)rhs)txt)inTxt, char * outFile)addrPtr)addrPtr).TH "StartIt" 3 "5 Dec 2010" "Version Version 0.1.1" "Arduino Ethernet Shield/USB Interface Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StartIt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStartIt\fP (\fBArduino\fP obj)"
.br
.RI "\fICONSTRUCTOR: \fBStartIt()\fP Class default constructor. \fP"
.ti -1c
.RI "\fB~StartIt\fP ()"
.br
.RI "\fIDESTRUCTOR: \fB~StartIt()\fP Class destructor. \fP"
.ti -1c
.RI "void \fBrun_it\fP ()"
.br
.RI "\fIMETHOD: \fBrun_it()\fP Runs the main code we wish to execute on the microcontroller. \fP"
.ti -1c
.RI "void \fBsetDateTime\fP (char *inTxt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file StartIt.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StartIt::StartIt (\fBArduino\fP obj)"
.PP
CONSTRUCTOR: \fBStartIt()\fP Class default constructor. \fBParameters:\fP
.RS 4
\fI\fBArduino\fP\fP obj 
.RE
.PP

.PP
Definition at line 21 of file StartIt.cpp.
.SS "StartIt::~StartIt ()"
.PP
DESTRUCTOR: \fB~StartIt()\fP Class destructor. 
.PP
Definition at line 65 of file StartIt.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void StartIt::run_it ()"
.PP
METHOD: \fBrun_it()\fP Runs the main code we wish to execute on the microcontroller. 
.PP
Definition at line 33 of file StartIt.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Ethernet Shield/USB Interface Project from the source code.
